name: "Build & Push Backend - Project 2"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BE_IMAGE: "${{ secrets.DOCKERHUB_USERNAME }}/project2-be"

jobs:
  build_backend:
    name: Build & Push Backend
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ“ Generate Version Tag
        id: version
        run: echo "backend=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: ğŸ” DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ§° Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ—ï¸ Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./ecommerce-app-backend
          push: true
          tags: |
            ${{ env.BE_IMAGE }}:${{ steps.version.outputs.backend }}
            ${{ env.BE_IMAGE }}:latest
